version: "3"
services:
  db_ecom:
    image: mysql:5.7
    container_name: db_ecom
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      TZ: America/Sao_Paulo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  api_erp:
    build: .
    depends_on:
      db_ecom:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_SITE: ${MYSQL_DATABASE_SITE}
      MYSQL_USER_DB2: ${MYSQL_USER_DB2}
      MYSQL_PASSWORD_DB2: ${MYSQL_PASSWORD_DB2}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      TZ: America/Sao_Paulo

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
